"""
Scan Workflow Helper Functions
Extracted from large scan workflow functions for better maintainability
"""

import uuid
from datetime import date, datetime
from typing import Any, Dict, Tuple

import structlog

from app.models.scan_models import ScanInRequest, ScanOutRequest, sanitize_text_input

logger = structlog.get_logger()


class ProductValidator:
    """Handles product validation logic for scan workflows"""

    @staticmethod
    async def validate_or_prepare_product(
        sku: str, store_id: str, read_ops
    ) -> dict[str, Any]:
        """Validate product exists or prepare data for creation"""
        # This would check if product exists in database
        # For MVP, we'll prepare data for frontend to create via Supabase

        # Sanitize SKU
        clean_sku = sanitize_text_input(sku)

        # For now, return prepared product info
        # In full implementation, this would query the database
        return {
            "product_id": str(uuid.uuid4()),  # Will be generated by Supabase
            "sku": clean_sku,
            "needs_creation": True,  # Indicates frontend should create product
            "suggested_category": CategorySuggester.suggest_category_from_sku(clean_sku),
            "validation_status": "prepared",
        }


class CategorySuggester:
    """Handles category suggestion logic"""

    @staticmethod
    def suggest_category_from_sku(sku: str) -> str:
        """Suggest category based on SKU patterns"""
        sku_lower = sku.lower()

        if any(
            word in sku_lower
            for word in ["apple", "banana", "fruit", "vegetable", "produce"]
        ):
            return "fresh_produce"
        elif any(word in sku_lower for word in ["bread", "bakery", "pastry"]):
            return "bakery_fresh"
        elif any(word in sku_lower for word in ["milk", "dairy", "cheese", "yogurt"]):
            return "dairy"
        elif any(word in sku_lower for word in ["meat", "fish", "chicken", "beef"]):
            return "fresh_meat_fish"
        elif any(word in sku_lower for word in ["frozen"]):
            return "frozen"
        else:
            return "dry_goods"


class BatchNumberGenerator:
    """Handles batch number generation"""

    @staticmethod
    async def generate_batch_number(store_id: str, sku: str, expiry_date: date) -> str:
        """Generate unique batch number"""
        date_str = expiry_date.strftime("%Y%m%d")
        timestamp = datetime.now().strftime("%H%M%S")
        store_prefix = store_id[:8] if len(store_id) >= 8 else store_id
        sku_prefix = sku[:10] if len(sku) >= 10 else sku

        return f"{store_prefix}_{sku_prefix}_{date_str}_{timestamp}"


class ScoringCalculator:
    """Handles scoring calculations for scan workflows"""

    @staticmethod
    def calculate_initial_score(
        expiry_date: date, cost_price: float | None, selling_price: float | None
    ) -> tuple[float, str, list[str], list[str]]:
        """
        Calculate initial score for immediate feedback

        Returns:
            Tuple of (initial_score, urgency_level, recommendations, warnings)
        """
        recommendations = []
        warnings = []
        
        days_to_expiry = (expiry_date - date.today()).days

        if days_to_expiry <= 0:
            initial_score = 1.0
            urgency_level = "critical"
            recommendations.append("Product already expired - immediate action required")
        elif days_to_expiry <= 1:
            initial_score = 0.95
            urgency_level = "critical"
            recommendations.append("Expires tomorrow - apply discount immediately")
        elif days_to_expiry <= 3:
            initial_score = 0.8
            urgency_level = "high"
            recommendations.append("Expires soon - monitor closely and prepare discounts")
        elif days_to_expiry <= 7:
            initial_score = 0.6
            urgency_level = "medium"
            recommendations.append("Expires within a week - track sales velocity")
        else:
            initial_score = 0.2
            urgency_level = "low"
            recommendations.append("Good shelf life - monitor regularly")

        # Add warnings for edge cases
        if days_to_expiry < 0:
            warnings.append(f"Product expired {abs(days_to_expiry)} days ago")
        elif days_to_expiry > 365:
            warnings.append("Very long expiry date - please verify accuracy")

        if cost_price and selling_price:
            if cost_price >= selling_price:
                warnings.append("Cost price equals or exceeds selling price")

        return initial_score, urgency_level, recommendations, warnings


class BatchDataCreator:
    """Handles batch data creation for scan-in workflow"""

    @staticmethod
    def create_batch_creation_data(
        batch_data: ScanInRequest,
        product_info: dict[str, Any],
        store_id: str,
        batch_number: str,
        user_id: str,
    ) -> dict[str, Any]:
        """Create batch data for creation (via frontend to Supabase)"""
        return {
            "batch_id": str(uuid.uuid4()),
            "product_id": product_info.get("product_id"),
            "store_id": store_id,
            "batch_number": batch_number,
            "initial_quantity": float(batch_data.quantity),
            "current_quantity": float(batch_data.quantity),
            "expiry_date": batch_data.expiry_date.isoformat(),
            "manufacture_date": batch_data.manufacture_date.isoformat()
            if batch_data.manufacture_date
            else None,
            "cost_price": batch_data.cost_price,
            "selling_price": batch_data.selling_price,
            "location_code": batch_data.location_code,
            "status": "active",
            "created_by": user_id,
            "notes": batch_data.notes,
        }


class ScanInProcessor:
    """Main processor for scan-in workflow"""

    def __init__(self):
        self.product_validator = ProductValidator()
        self.batch_generator = BatchNumberGenerator()
        self.scoring_calculator = ScoringCalculator()
        self.batch_creator = BatchDataCreator()

    async def process_scan_in(
        self,
        store_id: str,
        batch_data: ScanInRequest,
        read_ops,
        user_id: str,
    ) -> tuple[dict[str, Any], str, float, str, list[str], list[str]]:
        """
        Process scan-in workflow

        Returns:
            Tuple of (batch_creation_data, batch_number, initial_score, urgency_level, recommendations, warnings)
        """
        # Validate product exists or prepare for creation
        product_info = await self.product_validator.validate_or_prepare_product(
            batch_data.product_sku, store_id, read_ops
        )

        # Generate batch number if not provided
        if not batch_data.batch_number:
            batch_number = await self.batch_generator.generate_batch_number(
                store_id, batch_data.product_sku, batch_data.expiry_date
            )
        else:
            batch_number = sanitize_text_input(batch_data.batch_number)

        # Prepare batch data for creation
        batch_creation_data = self.batch_creator.create_batch_creation_data(
            batch_data, product_info, store_id, batch_number, user_id
        )

        # Calculate initial score for immediate feedback
        initial_score, urgency_level, recommendations, warnings = (
            self.scoring_calculator.calculate_initial_score(
                batch_data.expiry_date, batch_data.cost_price, batch_data.selling_price
            )
        )

        return (
            batch_creation_data,
            batch_number,
            initial_score,
            urgency_level,
            recommendations,
            warnings,
        )


class QuantityValidator:
    """Handles quantity validation for scan-out workflow"""

    @staticmethod
    def validate_quantity(
        batch_data: dict[str, Any], scan_out_data: ScanOutRequest
    ) -> tuple[float, str]:
        """
        Validate quantity and calculate new status

        Returns:
            Tuple of (new_quantity, new_status)
        """
        from app.models.scan_models import ScanWorkflowException

        current_quantity = batch_data["current_quantity"]
        if scan_out_data.quantity_moved > current_quantity:
            raise ScanWorkflowException(
                f"Cannot move {scan_out_data.quantity_moved} items - only {current_quantity} available",
                workflow="scan_out",
                error_code="INSUFFICIENT_QUANTITY",
                status_code=400,
            )

        # Calculate new quantity and status
        new_quantity = current_quantity - scan_out_data.quantity_moved
        new_status = "active" if new_quantity > 0 else "sold"

        if scan_out_data.action in ["discarded", "donated"]:
            if new_quantity == 0:
                new_status = scan_out_data.action.value

        return new_quantity, new_status


class FinancialImpactCalculator:
    """Handles financial impact calculations for scan-out workflow"""

    @staticmethod
    def calculate_financial_impact(
        scan_out_data: ScanOutRequest, batch_data: dict[str, Any]
    ) -> tuple[float, float]:
        """
        Calculate financial impact

        Returns:
            Tuple of (revenue_impact, waste_prevented)
        """
        revenue_impact = 0.0
        waste_prevented = 0.0

        if scan_out_data.action in ["sold_full_price", "sold_discounted"]:
            selling_price = (
                scan_out_data.actual_selling_price or batch_data["selling_price"]
            )
            revenue_impact = selling_price * scan_out_data.quantity_moved

            if scan_out_data.action == "sold_discounted":
                waste_prevented = revenue_impact  # Revenue recovered vs total loss

        elif scan_out_data.action == "donated":
            # Estimate waste prevented value (cost recovery + social impact)
            cost_value = batch_data["cost_price"] * scan_out_data.quantity_moved
            waste_prevented = cost_value * 0.7  # Estimated social value

        return revenue_impact, waste_prevented


class ActionDataCreator:
    """Handles action data creation for scan-out workflow"""

    @staticmethod
    def create_action_data(
        scan_out_data: ScanOutRequest,
        batch_id: str,
        store_id: str,
        batch_data: dict[str, Any],
        revenue_impact: float,
        waste_prevented: float,
        user_id: str,
    ) -> dict[str, Any]:
        """Create action record data"""
        action_id = str(uuid.uuid4())
        return {
            "action_id": action_id,
            "batch_id": batch_id,
            "store_id": store_id,
            "action_type": scan_out_data.action.value,
            "original_price": batch_data["selling_price"],
            "new_price": scan_out_data.actual_selling_price,
            "discount_percent": scan_out_data.discount_percent,
            "quantity_sold": scan_out_data.quantity_moved,
            "executed_by": user_id,
            "notes": scan_out_data.notes,
            "channel": scan_out_data.channel,
            "customer_type": scan_out_data.customer_type,
            "revenue_impact": revenue_impact,
            "waste_prevented": waste_prevented,
        }


class ActionEffectivenessCalculator:
    """Calculates effectiveness scores for actions"""

    @staticmethod
    async def calculate_action_effectiveness(
        action_data: dict[str, Any], batch_data: dict[str, Any], scan_out_data: ScanOutRequest
    ) -> float:
        """Calculate effectiveness score for the action taken"""
        base_score = 0.5

        # Score based on action type and timing
        if scan_out_data.action in ["sold_full_price", "sold_discounted"]:
            base_score = 0.9

            # Bonus for timely action on expiring items
            days_to_expiry = (
                datetime.fromisoformat(batch_data["expiry_date"]).date() - date.today()
            ).days
            if days_to_expiry <= 1 and scan_out_data.action == "sold_discounted":
                base_score = 1.0  # Perfect - sold discounted item before expiry
            elif days_to_expiry <= 0:
                base_score = 0.7  # Still sold, but after expiry

        elif scan_out_data.action == "donated":
            base_score = 0.7  # Good social impact

        elif scan_out_data.action == "discarded":
            base_score = 0.1  # Waste occurred

        return min(1.0, max(0.0, base_score))


class RealtimeUpdateTrigger:
    """Handles real-time updates for scan workflows"""

    @staticmethod
    async def trigger_realtime_update(
        store_id: str, batch_id: str, update_data: dict[str, Any]
    ):
        """Trigger real-time update for frontend"""
        try:
            # In full implementation, this would integrate with Supabase real-time
            # For now, just log the update
            logger.info(
                "Real-time update triggered",
                store_id=store_id,
                batch_id=batch_id,
                update_type="scan_out",
                data=update_data,
            )
        except Exception as e:
            logger.warning("Real-time update failed", error=str(e))


class ScanOutProcessor:
    """Main processor for scan-out workflow"""

    def __init__(self):
        self.quantity_validator = QuantityValidator()
        self.financial_calculator = FinancialImpactCalculator()
        self.action_creator = ActionDataCreator()
        self.effectiveness_calculator = ActionEffectivenessCalculator()
        self.realtime_trigger = RealtimeUpdateTrigger()

    async def process_scan_out(
        self,
        store_id: str,
        batch_id: str,
        scan_out_data: ScanOutRequest,
        batch_data: dict[str, Any],
        user_id: str,
    ) -> tuple[str, float, str, float, float, float, dict[str, Any]]:
        """
        Process scan-out workflow

        Returns:
            Tuple of (action_id, new_quantity, new_status, effectiveness_score, revenue_impact, waste_prevented, update_data)
        """
        # Validate quantity and calculate new status
        new_quantity, new_status = self.quantity_validator.validate_quantity(
            batch_data, scan_out_data
        )

        # Calculate financial impact
        revenue_impact, waste_prevented = self.financial_calculator.calculate_financial_impact(
            scan_out_data, batch_data
        )

        # Prepare action record
        action_data = self.action_creator.create_action_data(
            scan_out_data, batch_id, store_id, batch_data, revenue_impact, waste_prevented, user_id
        )

        # Calculate effectiveness score
        effectiveness_score = await self.effectiveness_calculator.calculate_action_effectiveness(
            action_data, batch_data, scan_out_data
        )

        # Prepare real-time update data
        update_data = {
            "action": scan_out_data.action.value,
            "new_quantity": new_quantity,
            "status": new_status,
            "effectiveness_score": effectiveness_score,
        }

        # Trigger real-time update (async, don't wait)
        await self.realtime_trigger.trigger_realtime_update(store_id, batch_id, update_data)

        return (
            action_data["action_id"],
            new_quantity,
            new_status,
            effectiveness_score,
            revenue_impact,
            waste_prevented,
            update_data,
        )


class BarcodeProductLookup:
    """Handles barcode-based product lookups"""

    @staticmethod
    async def lookup_product_by_barcode(
        barcode: str, store_id: str, read_ops
    ) -> dict[str, Any] | None:
        """Look up product by barcode"""
        # This would query the database for existing products with this barcode
        # For MVP implementation, return None to indicate new product needed
        return None


class UrgencyCalculator:
    """Calculates urgency scores for scanned items"""

    @staticmethod
    def calculate_urgency_score(expiry_date: date, confidence_score: float | None) -> tuple[float, list[str]]:
        """
        Calculate urgency based on expiry date and confidence

        Returns:
            Tuple of (urgency_score, warnings)
        """
        warnings = []
        days_to_expiry = (expiry_date - date.today()).days
        urgency_score = 0.1

        if days_to_expiry <= 0:
            urgency_score = 1.0
        elif days_to_expiry <= 1:
            urgency_score = 0.95
        elif days_to_expiry <= 3:
            urgency_score = 0.8
        elif days_to_expiry <= 7:
            urgency_score = 0.6

        # Validate expiry date confidence
        if confidence_score is not None and confidence_score < 0.8:
            warnings.append(
                f"Low confidence on expiry date ({confidence_score:.2f}) - please verify"
            )

        return urgency_score, warnings