'use client'

import { AlertCircle, Brain, CheckCircle, ChevronDown, ChevronRight } from 'lucide-react'
import { useState } from 'react'
import { Badge } from '@/components/ui/badge'
import { Card } from '@/components/ui/card'
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible'

interface MappingRule {
  field: string
  description: string
  example: string
  required: boolean
  autoGenerated?: boolean
}

const CSV_MAPPING_RULES: MappingRule[] = [
  {
    field: 'SKU',
    description: 'Product identifier - auto-generated if missing',
    example: 'ABC123 → ABC123 (or auto: PROD_001)',
    required: false,
    autoGenerated: true,
  },
  {
    field: 'Product_Name / Name',
    description: 'Product display name',
    example: 'Organic Apples → Organic Apples',
    required: true,
  },
  {
    field: 'Category',
    description: 'Product category - determines shelf life defaults',
    example: 'Produce → 7 days shelf life',
    required: false,
  },
  {
    field: 'Price / Unit_Price',
    description: 'Product price - defaults to $0.00',
    example: '2.99 → $2.99 (or default: $0.00)',
    required: false,
    autoGenerated: true,
  },
  {
    field: 'Quantity',
    description: 'Inventory quantity',
    example: '50 → 50 units',
    required: true,
  },
  {
    field: 'Location_Code',
    description: 'Storage location - defaults to MAIN',
    example: 'COOLER → COOLER (or default: MAIN)',
    required: false,
    autoGenerated: true,
  },
  {
    field: 'Expiration_Date',
    description: 'Product expiry - calculated if missing',
    example: '2024-12-31 (or auto-calculated from category)',
    required: false,
    autoGenerated: true,
  },
]

const CATEGORY_DEFAULTS = [
  { category: 'Produce', shelfLife: '7 days', description: 'Fresh fruits and vegetables' },
  { category: 'Dairy', shelfLife: '14 days', description: 'Milk, cheese, yogurt' },
  { category: 'Meat', shelfLife: '3 days', description: 'Fresh meat and poultry' },
  { category: 'Packaged', shelfLife: '90 days', description: 'Canned and packaged goods' },
  { category: 'Frozen', shelfLife: '180 days', description: 'Frozen products' },
]

export function CSVMappingInfo() {
  const [showMappingRules, setShowMappingRules] = useState(false)
  const [showCategoryDefaults, setShowCategoryDefaults] = useState(false)

  return (
    <Card className="p-4">
      <div className="space-y-4">
        <div className="flex items-center gap-2">
          <Brain className="h-5 w-5 text-blue-500" />
          <h3 className="font-medium">Smart CSV Mapping</h3>
          <Badge variant="secondary" className="text-xs">
            Intelligent Processing
          </Badge>
        </div>

        <p className="text-sm text-muted-foreground">
          Our system automatically maps your CSV columns and fills in missing data using smart
          defaults.
        </p>

        {/* Field Mapping Rules */}
        <Collapsible open={showMappingRules} onOpenChange={setShowMappingRules}>
          <CollapsibleTrigger className="flex items-center gap-2 text-sm font-medium hover:text-primary">
            {showMappingRules ? (
              <ChevronDown className="h-4 w-4" />
            ) : (
              <ChevronRight className="h-4 w-4" />
            )}
            Field Mapping Rules ({CSV_MAPPING_RULES.length} supported fields)
          </CollapsibleTrigger>
          <CollapsibleContent className="mt-3">
            <div className="space-y-3">
              {CSV_MAPPING_RULES.map(rule => (
                <div key={rule.field} className="border rounded-lg p-3 bg-gray-50">
                  <div className="flex items-start justify-between mb-2">
                    <div className="flex items-center gap-2">
                      <code className="text-sm font-mono bg-white px-2 py-1 rounded">
                        {rule.field}
                      </code>
                      {rule.required ? (
                        <Badge variant="destructive" className="text-xs">
                          Required
                        </Badge>
                      ) : (
                        <Badge variant="secondary" className="text-xs">
                          Optional
                        </Badge>
                      )}
                      {rule.autoGenerated && (
                        <Badge variant="outline" className="text-xs text-blue-600">
                          <Brain className="h-3 w-3 mr-1" />
                          Smart Default
                        </Badge>
                      )}
                    </div>
                  </div>
                  <p className="text-sm text-gray-700 mb-2">{rule.description}</p>
                  <div className="text-xs text-gray-600 font-mono bg-white p-2 rounded border">
                    Example: {rule.example}
                  </div>
                </div>
              ))}
            </div>
          </CollapsibleContent>
        </Collapsible>

        {/* Category Defaults */}
        <Collapsible open={showCategoryDefaults} onOpenChange={setShowCategoryDefaults}>
          <CollapsibleTrigger className="flex items-center gap-2 text-sm font-medium hover:text-primary">
            {showCategoryDefaults ? (
              <ChevronDown className="h-4 w-4" />
            ) : (
              <ChevronRight className="h-4 w-4" />
            )}
            Category-Based Shelf Life ({CATEGORY_DEFAULTS.length} categories)
          </CollapsibleTrigger>
          <CollapsibleContent className="mt-3">
            <div className="flex flex-col gap-2">
              {CATEGORY_DEFAULTS.map(item => (
                <div
                  key={item.category}
                  className="flex items-center justify-between p-2 bg-gray-50 rounded"
                >
                  <div>
                    <span className="font-medium text-sm">{item.category}</span>
                    <p className="text-xs text-gray-600">{item.description}</p>
                  </div>
                  <Badge variant="outline" className="text-xs">
                    {item.shelfLife}
                  </Badge>
                </div>
              ))}
            </div>
          </CollapsibleContent>
        </Collapsible>

        {/* Processing Guarantees */}
        <div className="mt-4 p-3 bg-green-50 rounded-lg border border-green-200">
          <div className="flex items-start gap-2">
            <CheckCircle className="h-4 w-4 text-green-600 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-green-800">Processing Guarantees</p>
              <ul className="text-green-700 mt-1 space-y-1 text-xs">
                <li>• Missing SKUs are auto-generated with unique identifiers</li>
                <li>• Expiration dates calculated based on category rules</li>
                <li>• Prices default to $0.00 for manual entry later</li>
                <li>• All inventory gets MAIN location unless specified</li>
              </ul>
            </div>
          </div>
        </div>

        {/* Error Prevention */}
        <div className="mt-2 p-3 bg-blue-50 rounded-lg border border-blue-200">
          <div className="flex items-start gap-2">
            <AlertCircle className="h-4 w-4 text-blue-600 mt-0.5" />
            <div className="text-sm">
              <p className="font-medium text-blue-800">Error Prevention</p>
              <p className="text-blue-700 text-xs mt-1">
                Invalid data is automatically corrected or flagged with helpful warnings
              </p>
            </div>
          </div>
        </div>
      </div>
    </Card>
  )
}
