-- Migration: Restore objects removed by 20260219111710_remote_schema.sql
--
-- That file was generated by `supabase db pull` and incorrectly dropped several
-- objects without re-adding them, leaving remote in a degraded state:
--   - inventory.update_pil_updated_at() function
--   - trg_pil_updated_at trigger
--   - idx_pil_* indexes (unique constraints were preserved)
--   - product_integration_links column defaults, NOT NULL, and jsonb type
--   - trigger_refresh_user_permissions_on_stores on business.stores

-- ============================================================================
-- 1. Restore update_pil_updated_at function + trigger
-- ============================================================================

CREATE OR REPLACE FUNCTION inventory.update_pil_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_pil_updated_at ON inventory.product_integration_links;
CREATE TRIGGER trg_pil_updated_at
  BEFORE UPDATE ON inventory.product_integration_links
  FOR EACH ROW
  EXECUTE FUNCTION inventory.update_pil_updated_at();

-- ============================================================================
-- 2. Restore product_integration_links indexes
-- ============================================================================

CREATE INDEX IF NOT EXISTS idx_pil_integration_external
  ON inventory.product_integration_links (integration_type, external_id);

CREATE INDEX IF NOT EXISTS idx_pil_product_id
  ON inventory.product_integration_links (product_id);

CREATE INDEX IF NOT EXISTS idx_pil_integration_sku
  ON inventory.product_integration_links (integration_type, external_sku);

-- ============================================================================
-- 3. Restore product_integration_links column defaults, NOT NULL, and type
-- ============================================================================

-- Backfill NULLs before adding NOT NULL constraints
UPDATE inventory.product_integration_links SET created_at = now() WHERE created_at IS NULL;
UPDATE inventory.product_integration_links SET updated_at = now() WHERE updated_at IS NULL;

ALTER TABLE inventory.product_integration_links
  ALTER COLUMN created_at SET NOT NULL,
  ALTER COLUMN created_at SET DEFAULT now(),
  ALTER COLUMN updated_at SET NOT NULL,
  ALTER COLUMN updated_at SET DEFAULT now(),
  ALTER COLUMN is_authoritative SET DEFAULT false,
  ALTER COLUMN name_mismatch_logged SET DEFAULT false;

-- Restore metadata: was downgraded from jsonb to json by the bad migration
ALTER TABLE inventory.product_integration_links
  ALTER COLUMN metadata TYPE jsonb USING metadata::jsonb,
  ALTER COLUMN metadata SET DEFAULT '{}'::jsonb;

-- ============================================================================
-- 4. Restore trigger_refresh_user_permissions_on_stores
-- ============================================================================

DROP TRIGGER IF EXISTS trigger_refresh_user_permissions_on_stores ON business.stores;
CREATE TRIGGER trigger_refresh_user_permissions_on_stores
  AFTER UPDATE OF owner_id ON business.stores
  FOR EACH STATEMENT
  EXECUTE FUNCTION business.refresh_user_permissions();
